input {
  file {
    path => "/data/movies.csv"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  csv {
    separator => ","
    quote_char => '"'
    skip_header => true
    columns => ["movie_id", "title", "original_language", "release_date", "popularity", "vote_average", "vote_count", "overview"]
  }

  # Gérer les valeurs manquantes pour les champs numériques avant la conversion de type
  # Si un champ est une chaîne vide, le supprimer pour qu'Elasticsearch n'essaie pas de le convertir en nombre.
  if [popularity] == "" {
    mutate { remove_field => ["popularity"] }
  }
  if [vote_average] == "" {
    mutate { remove_field => ["vote_average"] }
  }
  if [vote_count] == "" {
    mutate { remove_field => ["vote_count"] }
  }

  # Gérer les valeurs manquantes pour la date avant la conversion
  if [release_date] == "" {
    mutate { remove_field => ["release_date"] }
  }

  # On cible uniquement movies_clean ici
  mutate {
    add_field => { "[@metadata][target_index]" => "movies_clean" }
    
    # Conversions de type documentées pour movies_clean
    convert => {
      "movie_id" => "integer"
      "popularity" => "float"
      "vote_average" => "float"
      "vote_count" => "integer"
    }
  }

  # Convertir la date si elle existe, puis supprimer le champ original
  if [release_date] {
    date {
      match => ["release_date", "dd-MM-yyyy", "yyyy-MM-dd"]
      target => "release_date_ts"
      remove_field => ["release_date"] # Supprimer le champ original après conversion
    }
  }

  mutate {
    remove_field => ["type", "@version", "host", "path", "message", "tags"] # Supprimer les tags par défaut de Logstash
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "%{[@metadata][target_index]}"
  }

  # Pour débug local, décommentez la ligne ci-dessous si besoin
  # stdout { codec => rubydebug }
}
