# Pipeline CLEAN : nettoyage et typage -> movies_clean
# TODO F3 : sera complete par Theophane (conversions, parsing date, split listes)
# Pour que Logstash demarre sans erreur, pipeline placeholder vide.

input {
  generator {
    count => 0
    message => "placeholder"
  }
}

filter { }

output { }
